-- MySQL Script generated by MySQL Workbench
-- Sat Nov 23 14:16:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EmployeeManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EmployeeManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EmployeeManagement` DEFAULT CHARACTER SET utf8 ;
USE `EmployeeManagement` ;

-- -----------------------------------------------------
-- Table `EmployeeManagement`.`EmployeePayments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmployeeManagement`.`EmployeePayments` (
  `emp_id` INT UNSIGNED NOT NULL,
  `expense_id` INT UNSIGNED NOT NULL,
  `payment_type` ENUM('salary', 'bonus') NOT NULL,
  `cost` FLOAT NOT NULL,
  `payment_date` DATE NOT NULL,
  PRIMARY KEY (`emp_id`, `expense_id`),
  INDEX `expenseIdPayment_idx` (`expense_id` ASC) VISIBLE,
  CONSTRAINT `empIdPayment`
    FOREIGN KEY (`emp_id`)
    REFERENCES `EmployeeManagement`.`Employees` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `expenseIdPayment`
    FOREIGN KEY (`expense_id`)
    REFERENCES `EmployeeManagement`.`Expenses` (`expense_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmployeeManagement`.`EmployeeTasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmployeeManagement`.`EmployeeTasks` (
  `emp_id` INT UNSIGNED NOT NULL,
  `task_id` INT UNSIGNED NOT NULL,
  `emp_status` ENUM('inactive', 'active', 'completed') NOT NULL,
  `date_assigned` DATE NOT NULL,
  `date_complete` DATE NULL,
  PRIMARY KEY (`emp_id`, `task_id`),
  CONSTRAINT `emp_id`
    FOREIGN KEY (`emp_id`)
    REFERENCES `EmployeeManagement`.`Employees` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `task_id`
    FOREIGN KEY (`task_id`)
    REFERENCES `EmployeeManagement`.`Tasks` (`task_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmployeeManagement`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmployeeManagement`.`Employees` (
  `emp_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `hire_date` DATE NOT NULL,
  `position` VARCHAR(45) NOT NULL,
  `salary` FLOAT NOT NULL,
  PRIMARY KEY (`emp_id`),
  UNIQUE INDEX `emp_id_UNIQUE` (`emp_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmployeeManagement`.`Expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmployeeManagement`.`Expenses` (
  `expense_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `expense_name` VARCHAR(45) NOT NULL,
  `expense_type` ENUM('materials', 'equipment', 'services', 'employee payment', 'travel', 'miscellaneous') NOT NULL,
  `expense_date` DATE NOT NULL,
  `cost` FLOAT NOT NULL,
  `project_id` INT UNSIGNED NULL,
  PRIMARY KEY (`expense_id`),
  CONSTRAINT `project_id_transaction`
    FOREIGN KEY (`project_id`)
    REFERENCES `EmployeeManagement`.`Projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmployeeManagement`.`Projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmployeeManagement`.`Projects` (
  `project_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `remaining_budget` FLOAT NOT NULL,
  `tasks_per_bonus` INT NOT NULL,
  `bonus_amount` FLOAT NOT NULL,
  `status` ENUM('not started', 'ongoing', 'completed', 'cancelled') NOT NULL,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EmployeeManagement`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EmployeeManagement`.`Tasks` (
  `task_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `task_name` VARCHAR(45) NOT NULL,
  `deadline` DATE NULL,
  `project_id` INT UNSIGNED NOT NULL,
  `status` ENUM('not started', 'ongoing', 'completed') NOT NULL,
  `date_complete` DATE NULL,
  PRIMARY KEY (`task_id`),
  UNIQUE INDEX `task_id_UNIQUE` (`task_id` ASC) VISIBLE,
  INDEX `project_id_idx` (`project_id` ASC) VISIBLE,
  CONSTRAINT `project_id_task`
    FOREIGN KEY (`project_id`)
    REFERENCES `EmployeeManagement`.`Projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
